Added a new flag to ignore unsuccessful bind
patroni/patroni pull request #3138
Opened 2024-08-27 05:54 UTC by sahilnaphade

This is a feature request made here : [Issue 3056](https://github.com/patroni/patroni/issues/3056)

Ask:
A new flag to ignore bind errors in the case where user wants re-validate parameters on a running Patroni cluster. In other words, if patroni is already running, Ansible (or other orchestrators) should get a successful code; even when the ports with `listen` specified are already bound by other process (most likely another Patroni instance)

Changes discussed and made:
A variable will be set when a flag is specified in CLI. If set, this flag should ignore the port as requested.

2024-08-27 06:38 UTC, CyberDem0n requested changes

2024-08-27 06:38 UTC, CyberDem0n commented on patroni/validator.py
> +VALIDATION_PARAMS : Dict[str, bool] = dict()
Variable with all capital letters in its name is treated by `pyright` as a constant, which is not entirely true for this specific case.
```suggestion
_validation_params : Dict[str, Any] = {}
```

Besides that, I would prefer to have a function that will modify global variable.

2024-08-27 06:38 UTC, CyberDem0n commented on patroni/validator.py
> +                    elif listen:
```suggestion
                    # Do not raise an exception if ignore_listen_port is set to True.
                    if listen and not _validation_params.get('ignore_listen_port', False):
```

2024-08-27 06:38 UTC, CyberDem0n commented on patroni/__main__.py
> +                        help='Ignore if the ports in `listen` are already bound by some process.')
Please update the help message to make it clear that this option works only for config validation.

2024-08-27 06:38 UTC, CyberDem0n commented on patroni/__main__.py
> +                        help='Ignore if the ports in `listen` are already bound by some process.')
Besides that, please update the `docstring` of this function.

2024-08-28 07:05 UTC, CyberDem0n commented on patroni/validator.py
> +    :param ignore_listen_port bool: Used to ignore the bind failures for the ports marked as `listen`
```suggestion
    :param ignore_listen_port: ignore the bind failures for the ports marked as `listen`.
```

2024-08-28 07:05 UTC, CyberDem0n commented on patroni/validator.py
> +    """Populates parameters used to fine-tune the validation of the Patroni config
```suggestion
    """Populate parameters used to fine-tune the validation of the Patroni config.
```

2024-08-28 07:05 UTC, CyberDem0n commented on patroni/__main__.py
> +        populate_validate_params(ignore_listen_port=args.ignore_listen_port)
```suggestion

        populate_validate_params(ignore_listen_port=args.ignore_listen_port)
```

2024-08-28 07:15 UTC, hughcapet commented on patroni/__main__.py
> +                        help='Ignores unsuccessful binds for the ports marked for `listen`.\
```suggestion
                        help='Ignore `listen` ports already in use.\
```

2024-08-28 07:15 UTC, hughcapet commented on patroni/__main__.py
> +      * ``--ignore-listen-port`` | ``-i`` -- used to ignore unsuccessful binds to the ports marked with `listen`.\
```suggestion
      * ``--ignore-listen-port`` | ``-i`` -- used to ignore ``listen`` ports already in use.\
```

2024-08-28 07:15 UTC, hughcapet commented on patroni/__main__.py
> +          Can be used only with --validate-config
```suggestion
          Can be used only with ``--validate-config``
```

2024-08-28 13:21 UTC, hughcapet commented
we also need to extend docs
https://github.com/patroni/patroni/blob/835d93951d437cacc24e3925272559cb20267c4d/docs/patroni_configuration.rst?plain=1#L241

2024-08-29 03:11 UTC, sahilnaphade commented
Hi @CyberDem0n and @hughcapet 
Thanks for your patience in reviewing my PR. I have updated the documentations as requested. Please let me know if anything else requires addressing.

2024-08-29 06:56 UTC, hughcapet commented on patroni/__main__.py
> +      * ``--ignore-listen-port`` | ``-i`` -- used to ignore ``listen`` ports already in use.\
```suggestion
      * ``--ignore-listen-port`` | ``-i`` -- used to ignore ``listen`` ports already in use.
```

2024-08-29 07:31 UTC, hughcapet approved these changes

2024-08-29 07:33 UTC, CyberDem0n approved these changes

2024-08-29 07:39 UTC, merged